### PR TITLE
Restored old Highlighter parsing

### PR DESCRIPTION
**Pull request by tonyt73**
The C++ changes commit broke the parsing of highlighters when changing parsers. LParser becomes nil and generates an exception.

### CODE REVIEW

**Comment by NilsHoyer** [comment]
@laconical77 did this in #18, since C++ had problems with nested declarations.

Now you please me to remove his modifications.

I don't know, how I should handle this. I'm a Delphi developer - not a C++ professional. And in the moment, I don't want to investigate more time to C++.

After I commited @laconical77 changes, he gave me a C++Builder Demo program. I was able to compile it and run it in 32 bit. So I don't understand, why you want to remove this change of him?

I really like the nested declarations inside Delphi - and I hated it to apply his modifications. But I want to have the BCEditor for C++Builder too. So I don't know, how I should handle your pull request. Can you assist me?

**Comment by tonyt73** [comment]
I will get the cpp demo working with the adjusted code

**Comment by NilsHoyer** [comment]
Why so complicated? What are the advantages?

**Comment by tonyt73** [comment]
Neither compiler (32/64) likes the nested declarations.
I can get the classic 32 bit CPP compiler to build the demo and run correctly.
I can get the 64 bit CPP compiler to build the 64 bit component package.
I can't get the 64 bit CPP compiler to build the 64 bit demo.
Only the 64 bit Delphi demo works.

I will close this PR and include the fix in the project file fixes

**Pull request closed without merging**
