### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by AhSh**
Few changes and fixes to Highlighters extracted from last lasee texteditor

### CODE REVIEW

**Comment by NilsHoyer** [comment]
All files are completely overwritten - not only the changes.

Maybe you didn't pull the latest update before you changed it...

**Comment by AhSh** [comment]
This is not my own update, its from new Lasee project (Text Editor Pro - http://texteditor.pro/)
I just made litle resource extraction.
http://texteditor.pro/index.php?page=history
How you can see in the history he made few fixes in Highligters and also he fixed Parser.
I checked some of highlighters and they works fine, this seems that he didn't make any changes in parser, only bug fixes, that makes new highlighters compatible with BCEditor.

**Comment by NilsHoyer** [comment]
Yes, I modified the highlighters - I mainly the spaces. Lasse had 3 spaces per indent - I reduced it to 2 spaces, to more compatible with the most textes.
Because of this, the normal merge doesn't work...

**Comment by AhSh** [comment]
Ok, all extracted highlighters in archive https://github.com/AhSh/BCEditor/blob/master/Highlighters/Highlighters.zip

**Comment by NilsHoyer** [comment]
... but they are still in a format with 3 space as indents - my files having 2 spaces. It's a lot of work to merge it. You don't want to do this ... but I should do it?

**Comment by AhSh** [comment]
Sorry I didn't understand about you mean. I'm was sure that merging doesn't required and you can overwrite files. Ok, I will do 2 spaces ))

**Comment by NilsHoyer** [comment]
.. now, I see the changes - and only the changes.

Lasse changed the format of the highlighters. So I can't simple overtake them. I have to change the `BCEditor.Highlighters.pas` file first.

But I appricated the changes - so I will try to overtake the changes soon. Thank you for your work!

**Comment by AhSh** [comment]
One more update, I've changed encoding to utf-8 from ansi

**Pull request merged**
