### PR TITLE
Project file refactor

### PR DESCRIPTION
**Pull request by tonyt73**
Return previous C++ revert back - but included Symbol reset to nil
Moved Project files into separate folders for each version of compiler 
Removed CPP/Delphi from project names
Removed Runtime from package name
CPP Project simply builds the Delphi files

### CODE REVIEW

**Comment by tonyt73** [comment]
Demo works in 32/64 for Delphi
Demo only works in 32 bit for C++ Builder

**Comment by NilsHoyer** [comment]
tonyt73, you are very active and you want to realize a lot of modification. Thank you for your work.

But I still don't understand, why you want to have this changes. What kind of problems do have to split the package files?

If the reasons for this the nested declarations, please give me some more time. I try to find out, if there is a way to keep them or if I have to push them out. If I can't find a good solution, I will try to push them out within the next few days completely.

**Comment by NilsHoyer** [comment]
Btw: How can I add a second (and third) commit to an existing PR? Yesterday, I tried to add a second commit to a PR of an other project, but where can I do this? If I just commit it, I can create a new PR, but I would add the commit to the PR, I opened before.

**Comment by NilsHoyer** [comment]
I asked at [StackOverflow](http://stackoverflow.com/questions/43758215/delphi-nested-declarations-in-cbuilder) about the problems with nested declarations. Until now, I didn't get an answer - but there were some people who asked about more details about this problems.

I really want to understand the problems about nested declarations for the C++Builder. Until now, without success.

**Comment by tonyt73** [comment]
I will investigate the nested declarations a little more.
I am interested in why it doesn't work either.

The reason for the change is that each project file has it own format for each compiler version.
If there is only a single project file then it would have to be say Delphi XE 4 or something low like that.
There should ideally be a project file for each version of Rad Studio that the project supports.
Each time a new Rad Studio loads an old version of a project file; it will upgrade it to the new version.

Also with regard to a single component dll source. Regardless of what compiler builds the component dlls (bpl) either can be used in the Rad Studio IDE. Since they are both built using the Delphi compiler with the exception of the main.cpp file built by C++ Builder; the Bpl's should be very much equivalent.
Though it is still preferable to have have Delphi build the BPLs and then install then into C++ Builder.
So there is no reason to make different versions of the BPL's which were made by different compilers.
One version of each BPL regardless of compiler used to build it.

**Comment by NilsHoyer** [comment]
Why do you believe each differnt version of the Delphi (or C++Builder) needs his own package files?

You are writing a lot of text and I should read it. This needs a lot of time. Also you are developing a lot of modifications. But I believe you are not able to match the point of what you are trying to tell. But focusing the main problem and handle it with some few word / modification are the way to offer efficient solutions (and software).

So please focus the main problem and offer answers to my questions. That assists me. If you are not able to do this, please spend your time with an other things. With that, you assist me not to handle your queries and offers.

**Comment by tonyt73** [comment]
If you read my explanation you would understand and I have answered your questions repeatedly.
Ignore the C++ builder change. That is the ONLY code change in this PR.

You need different package files because people use different versions of Rad Studio. Yes you can supply just the XE4 project file. But if people are submitting changes then the project files would have to be ignored. This means you need to hand edit the project file if you want to add/remove files. Which I guess is ok.
Other Delphi projects include a project file per major Rad Studio release. For example SynEdit.
You can cancel the PR; I don't really care.
I will keep my branch and just merge any changes I see into my branch.

Thank you again for the quite rude responses to my assistance.
Best of luck with "your" project.

**Comment by NilsHoyer** [comment]
Sometimes the best solution is not working to working together.

**Comment by tonyt73** [comment]
You need to review other Delphi component libraries.
Such as SynEdit, LMD Components which always provide different project files for different compilers.
The latest way you have setup the projects shows your in-experience.

**Pull request closed without merging**
